# Chapter 5, Part II

In [425]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Pandas:", pd.__version__)

Pandas: 3.0.6

## A fictional Cambodian online shop dataset
Every group acts as a data analyst helping a shop investigate sales.

In [426]:
sales = pd.DataFrame({
    'shop':['Phnom Penh','Siem Reap','Battambang','Kampot','Takeo','Kandal'],
    'category':['Bag','Watch','Bag','Watch','Bag','Watch'],
    'units':[15,9,20,12,8,18],
    'price_usd':[18,25,20,22,15,24],
    'rating':[4.7,4.2,np.nan,4.6,3.9,4.8]
}).set_index('shop')
sales['revenue'] = sales['units'] * sales['price_usd']
display(sales)

           category  units  price_usd  rating  revenue
shop
Phnom Penh      Bag     15         18     4.7      270
Siem Reap     Watch      9         25     4.2      225
Battambang      Bag     20         20     NaN      400
Kampot        Watch     12         22     4.6      264
Takeo           Bag      8         15     3.9      120
Kandal        Watch     18         24     4.8      432

---
## Mission 1: 1. Missing Shop Mystery

In [427]:
print(sales.reindex(['Kampot','Phnom Penh','Pursat']))
print(sales['units'].reindex(['Kampot','Pursat'], fill_value=0))

           category  units  price_usd  rating  revenue
shop
Kampot        Watch   12.0       22.0     4.6    264.0
Phnom Penh      Bag   15.0       18.0     4.7    270.0
Pursat          NaN    NaN        NaN     NaN      NaN
shop
Kampot    12
Pursat     0
Name: units, dtype: int64

### Student challenge
**Challenge**
1. Reorder rows to `Takeo`, `Kandal`, `Phnom Penh`, `Pursat`.
2. Explain why Pursat has `NaN`.
3. Reindex the `units` Series and replace missing labels with zero.
4. Reindex columns to `units`, `revenue`, `discount`.
5. Explain why reindexing is not the same as sorting.

In [428]:
# YOUR SOLUTION HERE
#1. 
print(sales.reindex(['Takeo','Kandal','Phnom Penh','Pursat']))
print("\n")
#2. 
print("Part2: Pursat has NaN because in the label doesn't exist in the sales.index that why when we reindex it has no data to fill in.")
print("\n")
#3. 
print(sales['units'].reindex(['Takeo','Kandal','Phnom Penh','Pursat'], fill_value=0))
print("\n")
#4.
print(sales.reindex(columns=['units','revenue','discount']))
print("\n")
#5.
print("Part5: In Python(specifically in Pandas), sorting arranges your existing data into a logical sequence,whereas reindexing conforms your data to match a specific new sequence or set of labels you provide.")

           category  units  price_usd  rating  revenue
shop
Takeo           Bag    8.0       15.0     3.9    120.0
Kandal        Watch   18.0       24.0     4.8    432.0
Phnom Penh      Bag   15.0       18.0     4.7    270.0
Pursat          NaN    NaN        NaN     NaN      NaN


Part2: Pursat has NaN because in the label doesn't exist in the sales.index that why when we reindex it has no data to fill in.


shop
Takeo          8
Kandal        18
Phnom Penh    15
Pursat         0
Name: units, dtype: int64


            units  revenue  discount
shop
Phnom Penh     15      270       NaN
Siem Reap       9      225       NaN
Battambang     20      400       NaN
Kampot         12      264       NaN
Takeo           8      120       NaN
Kandal         18      432       NaN


Part5: In Python(specifically in Pandas), sorting arranges your existing data into a logical sequence,whereas reindexing conforms your data to match a specific new sequence or set of labels you provide.

---
## Mission 2: 2. Data Cleanup Race

In [429]:
display(sales.drop(index='Takeo'))
display(sales.drop(columns=['rating']))

           category  units  price_usd  rating  revenue
shop
Phnom Penh      Bag     15         18     4.7      270
Siem Reap     Watch      9         25     4.2      225
Battambang      Bag     20         20     NaN      400
Kampot        Watch     12         22     4.6      264
Kandal        Watch     18         24     4.8      432

           category  units  price_usd  revenue
shop
Phnom Penh      Bag     15         18      270
Siem Reap     Watch      9         25      225
Battambang      Bag     20         20      400
Kampot        Watch     12         22      264
Takeo           Bag      8         15      120
Kandal        Watch     18         24      432

### Student challenge
**Challenge**
1. Remove `Kampot` and `Takeo`.
2. Remove `category` and `rating` columns.
3. Remove both those rows and columns in one expression.
4. Verify that `sales` still has six rows.

In [430]:
# YOUR SOLUTION HERE
# YOUR SOLUTION HERE
print(sales)
print(sales.drop(index = ['Kampot','Takeo']))
#if more than 2 we need to use []
print(sales.drop(columns=['category','rating']))

print(sales.drop(index = ['Kampot','Takeo'],columns=['category','rating']))
print(sales.shape)

           category  units  price_usd  rating  revenue
shop
Phnom Penh      Bag     15         18     4.7      270
Siem Reap     Watch      9         25     4.2      225
Battambang      Bag     20         20     NaN      400
Kampot        Watch     12         22     4.6      264
Takeo           Bag      8         15     3.9      120
Kandal        Watch     18         24     4.8      432
           category  units  price_usd  rating  revenue
shop
Phnom Penh      Bag     15         18     4.7      270
Siem Reap     Watch      9         25     4.2      225
Battambang      Bag     20         20     NaN      400
Kandal        Watch     18         24     4.8      432
            units  price_usd  revenue
shop
Phnom Penh     15         18      270
Siem Reap       9         25      225
Battambang     20         20      400
Kampot         12         22      264
Takeo           8         15      120
Kandal         18         24      432
            units  price_usd  revenue
shop
Phnom Penh     15         18      270
Siem Reap       9         25      225
Battambang     20         20      400
Kandal         18         24      432
(6, 5)

---
## Mission 3: 3. Find the VIP Shops — filtering, loc, iloc

In [431]:
display(sales.loc['Kampot',['units','revenue']])
display(sales.iloc[:2,:3])
display(sales[sales['revenue']>=300])

units       12
revenue    264
Name: Kampot, dtype: int64

           category  units  price_usd
shop
Phnom Penh      Bag     15         18
Siem Reap     Watch      9         25

           category  units  price_usd  rating  revenue
shop
Battambang      Bag     20         20     NaN      400
Kandal        Watch     18         24     4.8      432

### Student challenge
**Challenge**
1. Show `units` and `revenue` for Phnom Penh and Kandal with `loc`.
2. Select the first three rows and first two columns with `iloc`.
3. Find shops with revenue above $300 **and** units at least 15.
4. Display rows from `Siem Reap` through `Kampot` using label slicing.
5. Explain why `series.iloc[-1]` is safer than `series[-1]` when index labels are integers.

In [432]:
# YOUR SOLUTION HERE
#1. Show `units` and `revenue` for Phnom Penh and Kandal with `loc`.
display(sales.loc[['Phnom Penh', 'Kandal'],['units', 'revenue']])
#2. Select the first three rows and first two columns with `iloc`.
select = sales.iloc[:3, :2]
display(select)
#3. Find shops with revenue above $300 **and** units at least 15.
display(sales[(sales['revenue'] > 300) & (sales['units'] >= 15)])
#4. Display rows from `Siem Reap` through `Kampot` using label slicing.
display(sales.loc['Siem Reap':'Kampot'])
#5. Explain why `series.iloc[-1]` is safer than `series[-1]` when index labels are integers.
#because series.iloc[-1] is always calling the value at the last position, however series[-1] is possible whenever there's the index was assigned as -1.

            units  revenue
shop
Phnom Penh     15      270
Kandal         18      432

           category  units
shop
Phnom Penh      Bag     15
Siem Reap     Watch      9
Battambang      Bag     20

           category  units  price_usd  rating  revenue
shop
Battambang      Bag     20         20     NaN      400
Kandal        Watch     18         24     4.8      432

           category  units  price_usd  rating  revenue
shop
Siem Reap     Watch      9         25     4.2      225
Battambang      Bag     20         20     NaN      400
Kampot        Watch     12         22     4.6      264

---
## Mission 4: 4. Two Accountants Disagree — alignment and arithmetic

In [433]:
week1=pd.Series({'Phnom Penh':100,'Kampot':80,'Takeo':60})
week2=pd.Series({'Kampot':70,'Takeo':90,'Kandal':40})
display(week1+week2)
display(week1.add(week2,fill_value=0))

Kampot        150.0
Kandal          NaN
Phnom Penh      NaN
Takeo         150.0
dtype: float64

Kampot        150.0
Kandal         40.0
Phnom Penh    100.0
Takeo         150.0
dtype: float64

### Student challenge
**Challenge (10 pts)**
1. Add the two weeks normally.
2. Add them with `fill_value=0`.
3. Calculate week2 minus week1 with `sub(fill_value=0)`.
4. Explain why Phnom Penh is missing in ordinary addition.
5. Subtract a Series of `units` from matching DataFrame column `units` using explicit column alignment.

In [434]:
# YOUR SOLUTION HERE
#1. Add the two weeks normally
print ("Two week:\n", week1 + week2)
#2. Add them with `fill_value=0`
print (week1.add(week2, fill_value = 0))
#3. Calculate week2 minus week1 with `sub(fill_value=0)`.
print (week2.sub(week1, fill_value = 0))
# #4. Explain why Phnom Penh is missing in ordinary addition.
# because there is no PP in week 2 so normal addition cannot calculate

#5. Subtract a Series of `units` from matching DataFrame column `units` using explicit column alignment.
sales.loc[:, "units":"price_usd"]
sales["units"] -= 5
sales["price_usd"] -= 10
sales[['units', 'price_usd']]

Two week:
 Kampot        150.0
Kandal          NaN
Phnom Penh      NaN
Takeo         150.0
dtype: float64
Kampot        150.0
Kandal         40.0
Phnom Penh    100.0
Takeo         150.0
dtype: float64
Kampot        -10.0
Kandal         40.0
Phnom Penh   -100.0
Takeo          30.0
dtype: float64

            units  price_usd
shop
Phnom Penh     10          8
Siem Reap       4         15
Battambang     15         10
Kampot          7         12
Takeo           3          5
Kandal         13         14

---
## Mission 5: 5. Function Factory — apply, map and NumPy

In [435]:
numeric=sales[['units','price_usd','revenue']]
print(numeric.apply(lambda x:x.max()-x.min()))
print(numeric.apply(lambda x:x.max()-x.min(),axis=1))
print(sales['category'].map({'Bag':'👜 Bag','Watch':'⌚ Watch'}))

units         12
price_usd     10
revenue      312
dtype: int64
shop
Phnom Penh    262
Siem Reap     221
Battambang    390
Kampot        257
Takeo         117
Kandal        419
dtype: int64
shop
Phnom Penh      👜 Bag
Siem Reap     ⌚ Watch
Battambang      👜 Bag
Kampot        ⌚ Watch
Takeo           👜 Bag
Kandal        ⌚ Watch
Name: category, dtype: str

### Student challenge
**Challenge (10 pts)**
1. Calculate the range (max − min) for each numeric column.
2. Calculate the range for each row.
3. Create a `revenue_level` Series with `High` when revenue ≥300, else `Low`, using `map`.
4. Round all values in a numeric DataFrame to one decimal place using element-wise mapping.
5. Explain why applying max−min directly to mixed string/numeric columns may raise a TypeError.

In [436]:
# YOUR SOLUTION HERE
#task 1
#print(numeric)
print(numeric.apply(lambda x:x.max()-x.min(), axis=0))

#task 2
print(numeric.apply(lambda x:x.max()-x.min(), axis=1))

#task 3
revnenue_level = pd.Series(map(lambda x: 'High' if x >= 300 else 'Low', numeric['revenue']))
print(revnenue_level)

#task 4
print(numeric.map(lambda x: round(float(x),1)))

#task5

units         12
price_usd     10
revenue      312
dtype: int64
shop
Phnom Penh    262
Siem Reap     221
Battambang    390
Kampot        257
Takeo         117
Kandal        419
dtype: int64
0     Low
1     Low
2    High
3     Low
4     Low
5    High
dtype: str
            units  price_usd  revenue
shop
Phnom Penh   10.0        8.0    270.0
Siem Reap     4.0       15.0    225.0
Battambang   15.0       10.0    400.0
Kampot        7.0       12.0    264.0
Takeo         3.0        5.0    120.0
Kandal       13.0       14.0    432.0

---
## Mission 6: 6. Sales Leaderboard — sorting, ranking, duplicate labels

In [437]:
display(sales.sort_values('revenue',ascending=False))
print(sales['units'].rank(ascending=False,method='min'))
repeated=pd.Series([3,4,5],index=['A','A','B']);print(repeated.index.is_unique);display(repeated.loc['A'])

           category  units  price_usd  rating  revenue
shop
Kandal        Watch     13         14     4.8      432
Battambang      Bag     15         10     NaN      400
Phnom Penh      Bag     10          8     4.7      270
Kampot        Watch      7         12     4.6      264
Siem Reap     Watch      4         15     4.2      225
Takeo           Bag      3          5     3.9      120

shop
Phnom Penh    3.0
Siem Reap     5.0
Battambang    1.0
Kampot        4.0
Takeo         6.0
Kandal        2.0
Name: units, dtype: float64
False

A    3
A    4
dtype: int64

### Student challenge
**Challenge**
1. Sort shops alphabetically.
2. Sort by revenue descending.
3. Create revenue ranks with highest revenue as rank 1.
4. Compare rank methods `min` and `dense` for `[10,10,8,6]`.
5. Construct a Series with duplicate labels and check `index.is_unique`.

In [438]:
# YOUR SOLUTION HERE
#1, sort shops alsphbetically A-Z
print("Here is sale table sort by alphabet:")
display(sales.sort_index())


#2, sort revenue by the highest first
# ascending=False puts the largest first. Without it, the smallest revenue would be on top.
print("Here is sale sort by revenue descending")
display(sales.sort_values('revenue',ascending = False)) #sorts by the data in the revenue column

#3, create the revenue ranks with highest revenues as rank 1 and display revenues + rank_revenues
#ascending = false give the highest revenues rank 1, method =min 
sales['rank_revenues']= sales['revenue'].rank(ascending = False, method = 'min').astype(int) #create new columns display rank of revenues from highest->smallest
display(sales[['revenue', 'rank_revenues']].sort_values('rank_revenues')) # display the table which is 2 collumns by sort values H->L


# compare rank methods min and dense for [10,10,8,6]
s = pd.Series([10,10,8,6])
compare = pd.DataFrame({
    'value':s,
    'min': s.rank(ascending =False, method ='min'),
    'dense': s.rank(ascending=False, method='dense'),   
    })
display(compare)

#Construct a Series with duplicate labels and check `index.is_unique`.
dup = pd.Series([1, 2, 3, 4], index=['X', 'X', 'Y', 'Z'])
print(dup.index.is_unique)
display(dup.loc['X'])

Here is sale table sort by alphabet:

           category  units  price_usd  rating  revenue
shop
Battambang      Bag     15         10     NaN      400
Kampot        Watch      7         12     4.6      264
Kandal        Watch     13         14     4.8      432
Phnom Penh      Bag     10          8     4.7      270
Siem Reap     Watch      4         15     4.2      225
Takeo           Bag      3          5     3.9      120

Here is sale sort by revenue descending

           category  units  price_usd  rating  revenue
shop
Kandal        Watch     13         14     4.8      432
Battambang      Bag     15         10     NaN      400
Phnom Penh      Bag     10          8     4.7      270
Kampot        Watch      7         12     4.6      264
Siem Reap     Watch      4         15     4.2      225
Takeo           Bag      3          5     3.9      120

            revenue  rank_revenues
shop
Kandal          432              1
Battambang      400              2
Phnom Penh      270              3
Kampot          264              4
Siem Reap       225              5
Takeo           120              6

   value  min  dense
0     10  1.0    1.0
1     10  1.0    1.0
2      8  3.0    2.0
3      6  4.0    3.0

False

X    1
X    2
dtype: int64

---
## Mission 7: 7. Statistics Detective — summaries and missing values

In [439]:
print(sales[['units','revenue']].sum())
print(sales[['units','revenue']].sum(axis='columns'))
print(sales['rating'].mean(skipna=False))
display(sales[['units','price_usd','revenue']].describe())

units        52
revenue    1711
dtype: int64
shop
Phnom Penh    280
Siem Reap     229
Battambang    415
Kampot        271
Takeo         123
Kandal        445
dtype: int64
nan

           units  price_usd     revenue
count   6.000000   6.000000    6.000000
mean    8.666667  10.666667  285.166667
std     4.844241   3.777124  115.173637
min     3.000000   5.000000  120.000000
25%     4.750000   8.500000  234.750000
50%     8.500000  11.000000  267.000000
75%    12.250000  13.500000  367.500000
max    15.000000  15.000000  432.000000

### Student challenge
**Challenge**
1. Find total revenue and average revenue.
2. Find the shop with maximum revenue using `idxmax`.
3. Calculate mean rating with `skipna=True` and `False`.
4. Show `describe()` for numeric columns.
5. Compute cumulative revenue in original row order.
6. Explain why cumulative values depend on row order.

In [440]:
# YOUR SOLUTION HERE
def nextStep():
    print("-" * 50)
#1.
print("1. Total revenue and average revenue")
total_revenue = sales['revenue'].sum()
avg_revenue = sales['revenue'].mean()
print(f"Total Revenue:   ${total_revenue}")
print(f"Average Revenue: ${avg_revenue:.2f}")
nextStep()

#2.
print("2. Shop with maximun revenue")
top_shop = sales['revenue'].idxmax()
print(f"The shop with maximun revenue is: {top_shop}")
nextStep()

#3.
print("3. Calculate mean rating using 'skipna=true' and 'false'")
mean_rating_false = sales['rating'].mean(skipna=False)
mean_rating_true = sales['rating'].mean(skipna=True)
print(f"Mean rating using 'skipna=true'  => {mean_rating_true:.2}")
print(f"Mean rating using 'skipna=false' => {mean_rating_false}")
nextStep()

#4. 
print("4. Show 'describe()' for numeric columns")
display(sales.describe())
nextStep()

#5. 
print("5. Compute cumulative revenue in original row order")
cumulative_revenue = sales['revenue'].cumsum()
print(cumulative_revenue)
nextStep()

#6.
print("6. Explain why culumative value depends on row order")
print("A cumulative sum is a running total calculated from top to bottom. Because each row's value")
print("is the sum of that row plus all rows before it, changing the row order changes which values")
print("are added first, resulting in different numbers for each shop.")

1. Total revenue and average revenue
Total Revenue:   $1711
Average Revenue: $285.17
--------------------------------------------------
2. Shop with maximun revenue
The shop with maximun revenue is: Kandal
--------------------------------------------------
3. Calculate mean rating using 'skipna=true' and 'false'
Mean rating using 'skipna=true'  => 4.4
Mean rating using 'skipna=false' => nan
--------------------------------------------------
4. Show 'describe()' for numeric columns

           units  price_usd    rating     revenue  rank_revenues
count   6.000000   6.000000  5.000000    6.000000       6.000000
mean    8.666667  10.666667  4.440000  285.166667       3.500000
std     4.844241   3.777124  0.378153  115.173637       1.870829
min     3.000000   5.000000  3.900000  120.000000       1.000000
25%     4.750000   8.500000  4.200000  234.750000       2.250000
50%     8.500000  11.000000  4.600000  267.000000       3.500000
75%    12.250000  13.500000  4.700000  367.500000       4.750000
max    15.000000  15.000000  4.800000  432.000000       6.000000

--------------------------------------------------
5. Compute cumulative revenue in original row order
shop
Phnom Penh     270
Siem Reap      495
Battambang     895
Kampot        1159
Takeo         1279
Kandal        1711
Name: revenue, dtype: int64
--------------------------------------------------
6. Explain why culumative value depends on row order
A cumulative sum is a running total calculated from top to bottom. Because each row's value
is the sum of that row plus all rows before it, changing the row order changes which values
are added first, resulting in different numbers for each shop.

---
## Mission 8: 8. Customer Preference Mystery — unique, value_counts, isin, get_indexer

In [441]:
print(sales['category'].unique())
print(sales['category'].value_counts())
display(sales[sales['category'].isin(['Bag'])])
print(pd.Index(['Bag','Watch']).get_indexer(['Watch','Bag','Other']))

<StringArray>
['Bag', 'Watch']
Length: 2, dtype: str
category
Bag      3
Watch    3
Name: count, dtype: int64

           category  units  price_usd  rating  revenue  rank_revenues
shop
Phnom Penh      Bag     10          8     4.7      270              3
Battambang      Bag     15         10     NaN      400              2
Takeo           Bag      3          5     3.9      120              6

[ 1  0 -1]

### Student challenge
**Challenge (10 pts)**
1. List distinct product categories.
2. Count shops by category.
3. Filter to `Bag` shops using `isin()`.
4. Get integer positions for `['Bag','Other','Watch']` relative to `['Bag','Watch']`.
5. Create a frequency table for `category` and a new `region` column using `.apply(pd.Series.value_counts).fillna(0)`.

In [442]:
# YOUR SOLUTION HERE
#1.list distinct product categories
print(sales["category"].unique())

#2.Count shops by category
print(sales["category"].value_counts())

#3.Filter to bag shop using isin()
print(sales[sales["category"].isin(['Bag'])])

#4.Get integer position for['Bag','Other','Watch'] relative to['Bag','Watch']
print(pd.Index(['Bag','Watch']).get_indexer(['Bag','Other','Watch']))

#5.Create a frequency table for category and new region column
sales['region'] = np.nan
frequency_table = sales[['category','region']].apply(pd.Series.value_counts).fillna(0)
print(frequency_table)

<StringArray>
['Bag', 'Watch']
Length: 2, dtype: str
category
Bag      3
Watch    3
Name: count, dtype: int64
           category  units  price_usd  rating  revenue  rank_revenues
shop
Phnom Penh      Bag     10          8     4.7      270              3
Battambang      Bag     15         10     NaN      400              2
Takeo           Bag      3          5     3.9      120              6
[ 0 -1  1]
       category  region
Bag           3     0.0
Watch         3     0.0

---
# 🏆 Final Team Boss Battle (20 points) — Network QoS Control Room
**Scenario:** Your group is monitoring a fictional network. The dataset has missing measurements and repeated service classes.

**Tasks:**
1. Show missing-value counts and a descriptive summary.
2. Filter devices with latency > 50 ms or packet loss > 1%.
3. Create a `QoS` column: `Good` only if latency ≤50 and packet loss ≤1, otherwise `Poor`.
4. Count Good/Poor devices and rank latency from highest to lowest.
5. Find mean latency for each QoS class using filtering (no `groupby` required).
6. Make a bar chart of QoS counts and explain one operational recommendation.

In [443]:
network=pd.DataFrame({'device':['A','B','C','D','E','F','G','H'],
'latency_ms':[15,68,42,np.nan,95,23,55,34],
'loss_pct':[0.2,1.8,0.7,0.4,2.5,0.1,1.2,0.6],
'slice':['eMBB','URLLC','eMBB','mMTC','URLLC','mMTC','eMBB','URLLC']}).set_index('device')
display(network)

        latency_ms  loss_pct  slice
device
A             15.0       0.2   eMBB
B             68.0       1.8  URLLC
C             42.0       0.7   eMBB
D              NaN       0.4   mMTC
E             95.0       2.5  URLLC
F             23.0       0.1   mMTC
G             55.0       1.2   eMBB
H             34.0       0.6  URLLC

In [444]:
# YOUR FINAL CHALLENGE SOLUTION HERE

# ⚡ Exit-ticket quiz
1. Does `loc` use labels or integer positions?
2. Why does `reindex` introduce `NaN`?
3. What is the difference between `sort_values` and `sort_index`?
4. What does `axis=1` mean for `apply`?
5. What is the difference between `unique()` and `value_counts()`?