# Chapter 5, Part II

In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Pandas:", pd.__version__)

Pandas: 3.0.6

## A fictional Cambodian online shop dataset
Every group acts as a data analyst helping a shop investigate sales.

In [116]:
sales = pd.DataFrame({
    'shop':['Phnom Penh','Siem Reap','Battambang','Kampot','Takeo','Kandal'],
    'category':['Bag','Watch','Bag','Watch','Bag','Watch'],
    'units':[15,9,20,12,8,18],
    'price_usd':[18,25,20,22,15,24],
    'rating':[4.7,4.2,np.nan,4.6,3.9,4.8]
}).set_index('shop')
sales['revenue'] = sales['units'] * sales['price_usd']
display(sales)

           category  units  price_usd  rating  revenue
shop
Phnom Penh      Bag     15         18     4.7      270
Siem Reap     Watch      9         25     4.2      225
Battambang      Bag     20         20     NaN      400
Kampot        Watch     12         22     4.6      264
Takeo           Bag      8         15     3.9      120
Kandal        Watch     18         24     4.8      432

---
## Mission 1: 1. Missing Shop Mystery

In [117]:
print(sales.reindex(['Kampot','Phnom Penh','Pursat']))
print(sales['units'].reindex(['Kampot','Pursat'], fill_value=0))

           category  units  price_usd  rating  revenue
shop
Kampot        Watch   12.0       22.0     4.6    264.0
Phnom Penh      Bag   15.0       18.0     4.7    270.0
Pursat          NaN    NaN        NaN     NaN      NaN
shop
Kampot    12
Pursat     0
Name: units, dtype: int64

### Student challenge
**Challenge**
1. Reorder rows to `Takeo`, `Kandal`, `Phnom Penh`, `Pursat`.
2. Explain why Pursat has `NaN`.
3. Reindex the `units` Series and replace missing labels with zero.
4. Reindex columns to `units`, `revenue`, `discount`.
5. Explain why reindexing is not the same as sorting.

In [118]:
# YOUR SOLUTION HERE
#1
n_sales = sales.reindex(['Takeo','Kandal','Phnom Penh','Pursat'])
print(n_sales)
#2
#Pursat has NaN because that label doesn’t exist in sales, so pandas creates the row with no data.
#3
n_units = sales['units'].reindex(['Takeo','Kandal','Phnom Penh','Pursat'], fill_value=0)
print(n_units)
#4
n2_units = sales.reindex(columns=['units','revenue','discount'],fill_value=0)
print(n2_units)
#5
# Sorting only reorders existing rows. Reindexing conforms to a new label set, so it can add, drop and reorder.

           category  units  price_usd  rating  revenue
shop
Takeo           Bag    8.0       15.0     3.9    120.0
Kandal        Watch   18.0       24.0     4.8    432.0
Phnom Penh      Bag   15.0       18.0     4.7    270.0
Pursat          NaN    NaN        NaN     NaN      NaN
shop
Takeo          8
Kandal        18
Phnom Penh    15
Pursat         0
Name: units, dtype: int64
            units  revenue  discount
shop
Phnom Penh     15      270         0
Siem Reap       9      225         0
Battambang     20      400         0
Kampot         12      264         0
Takeo           8      120         0
Kandal         18      432         0

---
## Mission 2: 2. Data Cleanup Race

In [119]:
display(sales.drop(index='Takeo'))
display(sales.drop(columns=['rating']))

           category  units  price_usd  rating  revenue
shop
Phnom Penh      Bag     15         18     4.7      270
Siem Reap     Watch      9         25     4.2      225
Battambang      Bag     20         20     NaN      400
Kampot        Watch     12         22     4.6      264
Kandal        Watch     18         24     4.8      432

           category  units  price_usd  revenue
shop
Phnom Penh      Bag     15         18      270
Siem Reap     Watch      9         25      225
Battambang      Bag     20         20      400
Kampot        Watch     12         22      264
Takeo           Bag      8         15      120
Kandal        Watch     18         24      432

### Student challenge
**Challenge**
1. Remove `Kampot` and `Takeo`.
2. Remove `category` and `rating` columns.
3. Remove both those rows and columns in one expression.
4. Verify that `sales` still has six rows.

In [120]:
# YOUR SOLUTION HERE
display(sales.drop(index = ['Kampot', 'Takeo']))
#2
display(sales.drop(columns=['category', 'rating']))
#3
display(sales.drop(index = ['Kampot','Takeo'], columns= ['category','rating']))
#4
print(sales.shape)

           category  units  price_usd  rating  revenue
shop
Phnom Penh      Bag     15         18     4.7      270
Siem Reap     Watch      9         25     4.2      225
Battambang      Bag     20         20     NaN      400
Kandal        Watch     18         24     4.8      432

            units  price_usd  revenue
shop
Phnom Penh     15         18      270
Siem Reap       9         25      225
Battambang     20         20      400
Kampot         12         22      264
Takeo           8         15      120
Kandal         18         24      432

            units  price_usd  revenue
shop
Phnom Penh     15         18      270
Siem Reap       9         25      225
Battambang     20         20      400
Kandal         18         24      432

(6, 5)

---
## Mission 3: 3. Find the VIP Shops — filtering, loc, iloc

In [121]:
display(sales.loc['Kampot',['units','revenue']])
display(sales.iloc[:2,:3])
display(sales[sales['revenue']>=300])

units       12
revenue    264
Name: Kampot, dtype: int64

           category  units  price_usd
shop
Phnom Penh      Bag     15         18
Siem Reap     Watch      9         25

           category  units  price_usd  rating  revenue
shop
Battambang      Bag     20         20     NaN      400
Kandal        Watch     18         24     4.8      432

### Student challenge
**Challenge**
1. Show `units` and `revenue` for Phnom Penh and Kandal with `loc`.
2. Select the first three rows and first two columns with `iloc`.
3. Find shops with revenue above $300 **and** units at least 15.
4. Display rows from `Siem Reap` through `Kampot` using label slicing.
5. Explain why `series.iloc[-1]` is safer than `series[-1]` when index labels are integers.

In [124]:
# YOUR SOLUTION HERE
display(sales.loc['Phnom Penh',['units','revenue']])
display(sales.iloc[:3, :2])
display(sales[(sales['revenue']>300) & (sales['units']>= 15)])

units       15
revenue    270
Name: Phnom Penh, dtype: int64

           category  units
shop
Phnom Penh      Bag     15
Siem Reap     Watch      9
Battambang      Bag     20

           category  units  price_usd  rating  revenue
shop
Battambang      Bag     20         20     NaN      400
Kandal        Watch     18         24     4.8      432

---
## Mission 4: 4. Two Accountants Disagree — alignment and arithmetic

In [ ]:
week1=pd.Series({'Phnom Penh':100,'Kampot':80,'Takeo':60})
week2=pd.Series({'Kampot':70,'Takeo':90,'Kandal':40})
display(week1+week2)
display(week1.add(week2,fill_value=0))

Kampot        150.0
Kandal          NaN
Phnom Penh      NaN
Takeo         150.0
dtype: float64

Kampot        150.0
Kandal         40.0
Phnom Penh    100.0
Takeo         150.0
dtype: float64

### Student challenge
**Challenge (10 pts)**
1. Add the two weeks normally.
2. Add them with `fill_value=0`.
3. Calculate week2 minus week1 with `sub(fill_value=0)`.
4. Explain why Phnom Penh is missing in ordinary addition.
5. Subtract a Series of `units` from matching DataFrame column `units` using explicit column alignment.

In [ ]:
# YOUR SOLUTION HERE

---
## Mission 5: 5. Function Factory — apply, map and NumPy

In [ ]:
numeric=sales[['units','price_usd','revenue']]
print(numeric.apply(lambda x:x.max()-x.min()))
print(numeric.apply(lambda x:x.max()-x.min(),axis=1))
print(sales['category'].map({'Bag':'👜 Bag','Watch':'⌚ Watch'}))

units         12
price_usd     10
revenue      312
dtype: int64
shop
Phnom Penh    255
Siem Reap     216
Battambang    380
Kampot        252
Takeo         112
Kandal        414
dtype: int64
shop
Phnom Penh      👜 Bag
Siem Reap     ⌚ Watch
Battambang      👜 Bag
Kampot        ⌚ Watch
Takeo           👜 Bag
Kandal        ⌚ Watch
Name: category, dtype: str

### Student challenge
**Challenge (10 pts)**
1. Calculate the range (max − min) for each numeric column.
2. Calculate the range for each row.
3. Create a `revenue_level` Series with `High` when revenue ≥300, else `Low`, using `map`.
4. Round all values in a numeric DataFrame to one decimal place using element-wise mapping.
5. Explain why applying max−min directly to mixed string/numeric columns may raise a TypeError.

In [ ]:
# YOUR SOLUTION HERE

---
## Mission 6: 6. Sales Leaderboard — sorting, ranking, duplicate labels
#Pen Kanha, Soun ChhunEy, Ket Chanrachana, Touch Tevy, Loeng Rotha, Dut David

In [ ]:
display(sales.sort_values('revenue',ascending=False))
print(sales['units'].rank(ascending=False,method='min'))
repeated=pd.Series([3,4,5],index=['A','A','B']);print(repeated.index.is_unique);display(repeated.loc['A'])

           category  units  price_usd  rating  revenue
shop
Kandal        Watch     18         24     4.8      432
Battambang      Bag     20         20     NaN      400
Phnom Penh      Bag     15         18     4.7      270
Kampot        Watch     12         22     4.6      264
Siem Reap     Watch      9         25     4.2      225
Takeo           Bag      8         15     3.9      120

shop
Phnom Penh    3.0
Siem Reap     5.0
Battambang    1.0
Kampot        4.0
Takeo         6.0
Kandal        2.0
Name: units, dtype: float64
False

A    3
A    4
dtype: int64

### Student challenge
**Challenge**
1. Sort shops alphabetically.
2. Sort by revenue descending.
3. Create revenue ranks with highest revenue as rank 1.
4. Compare rank methods `min` and `dense` for `[10,10,8,6]`.
5. Construct a Series with duplicate labels and check `index.is_unique`.

In [132]:
# YOUR SOLUTION HERE
alpha_sort_shop = sales.sort_index()
display(alpha_sort_shop)
#2
reve_desc = sales.sort_values('revenue',ascending = False)
display(reve_desc)
#3
reve_rank = sales['revenue'].rank(ascending=False)
display(reve_rank)
#4
s = pd.Series([10,10,8,6])
display(s.rank(ascending=False, method='min'))
display(s.rank(ascending=False, method='dense'))
#5
dup = pd.Series([1,2,3], index =['a','b','c'])
display(dup.index.is_unique)

           category  units  price_usd  rating  revenue
shop
Battambang      Bag     20         20     NaN      400
Kampot        Watch     12         22     4.6      264
Kandal        Watch     18         24     4.8      432
Phnom Penh      Bag     15         18     4.7      270
Siem Reap     Watch      9         25     4.2      225
Takeo           Bag      8         15     3.9      120

           category  units  price_usd  rating  revenue
shop
Kandal        Watch     18         24     4.8      432
Battambang      Bag     20         20     NaN      400
Phnom Penh      Bag     15         18     4.7      270
Kampot        Watch     12         22     4.6      264
Siem Reap     Watch      9         25     4.2      225
Takeo           Bag      8         15     3.9      120

shop
Phnom Penh    3.0
Siem Reap     5.0
Battambang    2.0
Kampot        4.0
Takeo         6.0
Kandal        1.0
Name: revenue, dtype: float64

0    1.0
1    1.0
2    3.0
3    4.0
dtype: float64

0    1.0
1    1.0
2    2.0
3    3.0
dtype: float64

True

---
## Mission 7: 7. Statistics Detective — summaries and missing values

In [ ]:
print(sales[['units','revenue']].sum())
print(sales[['units','revenue']].sum(axis='columns'))
print(sales['rating'].mean(skipna=False))
display(sales[['units','price_usd','revenue']].describe())

units        82
revenue    1711
dtype: int64
shop
Phnom Penh    285
Siem Reap     234
Battambang    420
Kampot        276
Takeo         128
Kandal        450
dtype: int64
nan

           units  price_usd     revenue
count   6.000000   6.000000    6.000000
mean   13.666667  20.666667  285.166667
std     4.844241   3.777124  115.173637
min     8.000000  15.000000  120.000000
25%     9.750000  18.500000  234.750000
50%    13.500000  21.000000  267.000000
75%    17.250000  23.500000  367.500000
max    20.000000  25.000000  432.000000

### Student challenge
**Challenge**
1. Find total revenue and average revenue.
2. Find the shop with maximum revenue using `idxmax`.
3. Calculate mean rating with `skipna=True` and `False`.
4. Show `describe()` for numeric columns.
5. Compute cumulative revenue in original row order.
6. Explain why cumulative values depend on row order.

In [ ]:
# YOUR SOLUTION HERE

---
## Mission 8: 8. Customer Preference Mystery — unique, value_counts, isin, get_indexer

In [ ]:
print(sales['category'].unique())
print(sales['category'].value_counts())
display(sales[sales['category'].isin(['Bag'])])
print(pd.Index(['Bag','Watch']).get_indexer(['Watch','Bag','Other']))

<StringArray>
['Bag', 'Watch']
Length: 2, dtype: str
category
Bag      3
Watch    3
Name: count, dtype: int64

           category  units  price_usd  rating  revenue
shop
Phnom Penh      Bag     15         18     4.7      270
Battambang      Bag     20         20     NaN      400
Takeo           Bag      8         15     3.9      120

[ 1  0 -1]

### Student challenge
**Challenge (10 pts)**
1. List distinct product categories.
2. Count shops by category.
3. Filter to `Bag` shops using `isin()`.
4. Get integer positions for `['Bag','Other','Watch']` relative to `['Bag','Watch']`.
5. Create a frequency table for `category` and a new `region` column using `.apply(pd.Series.value_counts).fillna(0)`.

In [ ]:
# YOUR SOLUTION HERE

---
# 🏆 Final Team Boss Battle (20 points) — Network QoS Control Room
**Scenario:** Your group is monitoring a fictional network. The dataset has missing measurements and repeated service classes.

**Tasks:**
1. Show missing-value counts and a descriptive summary.
2. Filter devices with latency > 50 ms or packet loss > 1%.
3. Create a `QoS` column: `Good` only if latency ≤50 and packet loss ≤1, otherwise `Poor`.
4. Count Good/Poor devices and rank latency from highest to lowest.
5. Find mean latency for each QoS class using filtering (no `groupby` required).
6. Make a bar chart of QoS counts and explain one operational recommendation.

In [ ]:
network=pd.DataFrame({'device':['A','B','C','D','E','F','G','H'],
'latency_ms':[15,68,42,np.nan,95,23,55,34],
'loss_pct':[0.2,1.8,0.7,0.4,2.5,0.1,1.2,0.6],
'slice':['eMBB','URLLC','eMBB','mMTC','URLLC','mMTC','eMBB','URLLC']}).set_index('device')
display(network)

        latency_ms  loss_pct  slice
device
A             15.0       0.2   eMBB
B             68.0       1.8  URLLC
C             42.0       0.7   eMBB
D              NaN       0.4   mMTC
E             95.0       2.5  URLLC
F             23.0       0.1   mMTC
G             55.0       1.2   eMBB
H             34.0       0.6  URLLC

In [ ]:
# YOUR FINAL CHALLENGE SOLUTION HERE

# ⚡ Exit-ticket quiz
1. Does `loc` use labels or integer positions?
2. Why does `reindex` introduce `NaN`?
3. What is the difference between `sort_values` and `sort_index`?
4. What does `axis=1` mean for `apply`?
5. What is the difference between `unique()` and `value_counts()`?